### ISSUE TITLE
mesalock linux ISO

### ISSUE THREAD

**Issue by duramen** [mesalock-linux/mesalock-distro#7] opened 2018-01-05 08:05 UTC
Can you provide the image?

Compile often wrong。。。。。

**Comment by mssun** [comment] 2018-01-05 21:05
Thanks for the report. It may be caused by a compilation dependency: `sphinx`. I am working on it.

**Comment by mssun** [comment] 2018-01-05 21:53
@duramen the issue is fixed by c944bef3edb676908990fadf6b00b320a1cdcc17

The build docker image in DockerHub is also updated. Please pull the latest image. Thanks.

For the pre-compiled images, we plan to release stable and nightly versions in recent days.

**Closed as completed by mssun** 2018-01-05 21:53 UTC
Labels: bug

**Comment by duramen** [comment] 2018-01-08 02:28
BTW,   Sphinx>=1.4.3

Otherwise


Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
